#!/usr/bin/env python3
"""
Prepare training data for SamskaraLLM from 5 sources (PRD Section 8).

Downloads external datasets from HuggingFace, converts each to ATMAN-compatible
format, and merges with synthetic ATMAN records into a unified training corpus.

Datasets:
  1. AtlasUnified/atlas-reasoning      → Buddhi + Manas (reasoning categories)
  2. ddrager/worker-safety-qa           → Chitta + Dharma (safety-critical judgment)
  3. AlienKevin/cot-logic-reasoning     → Manas-Buddhi Dialogue (chain-of-thought)
  4. metaeval/ethics                    → Dharma (ethical acceptability)
  5. data/training/*.jsonl              → All layers (synthetic ATMAN records)

Usage:
    python autoresearch/prepare.py --dry-run     # verify downloads, no data written
    python autoresearch/prepare.py               # full preparation
    python autoresearch/prepare.py --output-dir data/autoresearch
"""

import argparse
import json
import os
import pickle
import random
import sys
from pathlib import Path


# Dataset registry: HuggingFace ID, config, split, and target cognitive layers
DATASETS = {
    "atlas_reasoning": {
        "hf_id": "AtlasUnified/atlas-reasoning",
        "config": None,
        "split": "train",
        "target_layers": ["buddhi", "manas"],
        "description": "42 reasoning categories — deductive/inductive logic",
    },
    "worker_safety_qa": {
        "hf_id": "codelion/worker-safety-qa-eval",
        "config": None,
        "split": "test",
        "target_layers": ["chitta", "dharma"],
        "description": "Safety-critical judgment scenarios for worker protection",
    },
    "cot_logic_reasoning": {
        "hf_id": "Raymond-dev-546730/Open-CoT-Reasoning-Mini",
        "config": None,
        "split": "train",
        "target_layers": ["manas", "buddhi", "dialogue"],
        "description": "Chain-of-thought reasoning across diverse domains",
    },
    "metaeval_ethics": {
        "hf_id": "lighteval/hendrycks_ethics",
        "config": "commonsense",
        "split": "train",
        "target_layers": ["dharma"],
        "description": "Ethical scenarios labeled acceptable/unacceptable (parquet format)",
    },
    "synthetic_atman": {
        "hf_id": None,  # Local files
        "local_path": "data/training",
        "target_layers": ["all"],
        "description": "Synthetic ATMAN records generated by scripts/generate_atman_data.py",
    },
}


def convert_atlas_reasoning(example):
    """Convert Atlas-Reasoning record to ATMAN format."""
    # Columns: topic, subtopics
    instruction = example.get("topic", example.get("instruction", example.get("question", "")))
    subtopics = example.get("subtopics", example.get("response", example.get("answer", "")))
    response = str(subtopics)[:500] if subtopics else ""
    category = "reasoning"

    return {
        "source": "atlas_reasoning",
        "scenario": instruction,
        "domain": "cross_domain",
        "complexity": "medium",
        "manas_signals": [
            {"type": "PATTERN", "intensity": 0.7, "description": f"Reasoning pattern: {category}"},
        ],
        "buddhi_options": [
            {"option": response[:200], "dharma_score": 0.8, "reasoning": "Logical conclusion"},
        ],
        "selected_option": 0,
        "elevation_target": 1,
        "outcome_score": 0.6,
        "chitta_keywords": [category, "reasoning", "logic"],
        "decision_rationale": f"Applied {category} reasoning.",
        "text": f"[SCENARIO] {instruction}\n[DOMAIN] cross_domain [COMPLEXITY] medium\n"
                f"[BUDDHI_OPTIONS]\n  Option 0 *SELECTED* (dharma=0.8): {response[:200]}\n"
                f"[OUTCOME] 0.60",
    }


def convert_worker_safety(example):
    """Convert Worker Safety QA record to ATMAN format."""
    question = example.get("question", example.get("input", ""))
    answer = example.get("answer", example.get("output", ""))

    return {
        "source": "worker_safety_qa",
        "scenario": question,
        "domain": "compliance",
        "complexity": "high",
        "manas_signals": [
            {"type": "RISK", "intensity": 0.9, "description": "Worker safety risk identified"},
            {"type": "FEAR", "intensity": 0.6, "description": "Potential harm to workers"},
        ],
        "buddhi_options": [
            {"option": answer[:200], "dharma_score": 0.9, "reasoning": "Prioritizes worker safety"},
            {"option": "Defer to standard procedure", "dharma_score": 0.4, "reasoning": "May not address specific risk"},
        ],
        "selected_option": 0,
        "elevation_target": 1,
        "outcome_score": 0.7,
        "chitta_keywords": ["safety", "worker", "compliance", "risk", "protection"],
        "decision_rationale": "Prioritized worker safety over operational convenience.",
        "text": f"[SCENARIO] {question}\n[DOMAIN] compliance [COMPLEXITY] high\n"
                f"[BUDDHI_OPTIONS]\n  Option 0 *SELECTED* (dharma=0.9): {answer[:200]}\n"
                f"[OUTCOME] 0.70",
    }


def convert_cot_logic(example):
    """Convert CoT Logic Reasoning record to ATMAN format."""
    question = example.get("question", example.get("input", ""))
    chain = example.get("chain_of_thought", example.get("reasoning", example.get("output", "")))
    answer = example.get("answer", example.get("label", ""))

    return {
        "source": "cot_logic_reasoning",
        "scenario": question,
        "domain": "cross_domain",
        "complexity": "medium",
        "manas_signals": [
            {"type": "PATTERN", "intensity": 0.8, "description": "Logical pattern recognition"},
        ],
        "buddhi_options": [
            {"option": str(answer), "dharma_score": 0.85, "reasoning": chain[:200] if chain else "Logical deduction"},
        ],
        "selected_option": 0,
        "elevation_target": 1,
        "outcome_score": 0.75,
        "chitta_keywords": ["logic", "reasoning", "chain-of-thought", "deduction"],
        "decision_rationale": "Applied chain-of-thought reasoning for logical deduction.",
        "text": f"[SCENARIO] {question}\n[DOMAIN] cross_domain [COMPLEXITY] medium\n"
                f"[MANAS_SIGNALS]\n  PATTERN (0.8): Logical pattern recognition\n"
                f"[BUDDHI_OPTIONS]\n  Option 0 *SELECTED* (dharma=0.9): {str(answer)[:200]}\n"
                f"[DECISION] {chain[:200] if chain else 'Logical deduction'}\n"
                f"[OUTCOME] 0.75",
    }


def convert_metaeval_ethics(example):
    """Convert MetaEval Ethics record to ATMAN format."""
    text = example.get("input", example.get("text", example.get("scenario", "")))
    label = example.get("label", example.get("output", 0))

    # label: 0 = unacceptable, 1 = acceptable (varies by subset)
    is_acceptable = int(label) == 1 if isinstance(label, (int, float)) else str(label).lower() in ("1", "true", "acceptable")
    dharma_score = 0.85 if is_acceptable else 0.15

    return {
        "source": "metaeval_ethics",
        "scenario": text,
        "domain": "ethical_dilemma",
        "complexity": "high",
        "manas_signals": [
            {"type": "RISK", "intensity": 0.7, "description": "Ethical risk assessment"},
            {"type": "PATTERN", "intensity": 0.5, "description": "Historical ethical precedent"},
        ],
        "buddhi_options": [
            {"option": "Proceed as described", "dharma_score": dharma_score, "reasoning": "Ethical acceptability assessment"},
            {"option": "Reject / seek alternative", "dharma_score": 1.0 - dharma_score, "reasoning": "Counter-position"},
        ],
        "selected_option": 0 if is_acceptable else 1,
        "elevation_target": 1,
        "outcome_score": 0.6 if is_acceptable else -0.3,
        "chitta_keywords": ["ethics", "dharma", "acceptability", "moral", "judgment"],
        "decision_rationale": f"Scenario assessed as {'acceptable' if is_acceptable else 'unacceptable'} based on ethical alignment.",
        "text": f"[SCENARIO] {text}\n[DOMAIN] ethical_dilemma [COMPLEXITY] high\n"
                f"[BUDDHI_OPTIONS]\n  Option {'0 *SELECTED*' if is_acceptable else '0'} (dharma={dharma_score:.1f}): Proceed\n"
                f"  Option {'1' if is_acceptable else '1 *SELECTED*'} (dharma={1.0 - dharma_score:.1f}): Reject\n"
                f"[OUTCOME] {'0.60' if is_acceptable else '-0.30'}",
    }


CONVERTERS = {
    "atlas_reasoning": convert_atlas_reasoning,
    "worker_safety_qa": convert_worker_safety,
    "cot_logic_reasoning": convert_cot_logic,
    "metaeval_ethics": convert_metaeval_ethics,
}


def load_hf_dataset(hf_id, config, split, max_samples=None):
    """Load a HuggingFace dataset, handling common variations."""
    from datasets import load_dataset

    kwargs = {}
    if config:
        kwargs["name"] = config

    ds = load_dataset(hf_id, split=split, **kwargs)

    if max_samples and len(ds) > max_samples:
        ds = ds.select(range(max_samples))

    return ds


def load_local_atman(local_path):
    """Load local ATMAN JSONL files."""
    records = []
    for fname in ["train.jsonl", "val.jsonl"]:
        fpath = Path(local_path) / fname
        if fpath.exists():
            with open(fpath) as f:
                for line in f:
                    rec = json.loads(line.strip())
                    rec["source"] = "synthetic_atman"
                    records.append(rec)
    return records


def tokenize_for_autoresearch(records, max_seq_len=128):
    """Simple character-level tokenization for SamskaraMini autoresearch runs."""
    # Build vocabulary from all records
    all_text = ""
    for rec in records:
        all_text += rec.get("text", rec.get("scenario", "")) + "\n"

    chars = sorted(set(all_text))
    stoi = {c: i for i, c in enumerate(chars)}

    tokenized = []
    for rec in records:
        text = rec.get("text", rec.get("scenario", ""))
        ids = [stoi.get(c, 0) for c in text[:max_seq_len]]
        if len(ids) < 2:
            continue
        tokenized.append({
            "ids": ids,
            "elevation": float(rec.get("elevation_target", 0)),
            "outcome": float(rec.get("outcome_score", 0.0)),
        })

    return tokenized, len(chars), stoi


def main():
    parser = argparse.ArgumentParser(description="Prepare SamskaraLLM training data from 5 sources")
    parser.add_argument("--dry-run", action="store_true", help="Verify datasets download, don't write output")
    parser.add_argument("--output-dir", type=str, default="data/autoresearch", help="Output directory")
    parser.add_argument("--max-per-dataset", type=int, default=5000, help="Max samples per external dataset")
    parser.add_argument("--val-split", type=float, default=0.1, help="Validation split ratio")
    parser.add_argument("--max-seq-len", type=int, default=128, help="Max sequence length for tokenization")
    args = parser.parse_args()

    print("SamskaraLLM Data Preparation Pipeline (PRD Section 8)")
    print("=" * 60)

    all_records = []
    dataset_stats = {}

    # Process each dataset
    for ds_name, ds_info in DATASETS.items():
        print(f"\n--- {ds_name}: {ds_info['description']} ---")
        print(f"    Target layers: {', '.join(ds_info['target_layers'])}")

        if ds_info.get("hf_id"):
            # HuggingFace dataset
            hf_id = ds_info["hf_id"]
            print(f"    HuggingFace: {hf_id}")

            try:
                from datasets import load_dataset

                if args.dry_run:
                    # Dry run: load just 5 samples to verify
                    print(f"    [DRY RUN] Loading 5 samples to verify...")
                    kwargs = {"streaming": True}
                    if ds_info.get("config"):
                        kwargs["name"] = ds_info["config"]
                    ds = load_dataset(hf_id, split=ds_info["split"], **kwargs)
                    samples = list(ds.take(5))
                    print(f"    [DRY RUN] OK — loaded {len(samples)} samples")
                    print(f"    [DRY RUN] Columns: {list(samples[0].keys()) if samples else 'empty'}")
                    if samples:
                        converter = CONVERTERS[ds_name]
                        converted = converter(samples[0])
                        print(f"    [DRY RUN] Conversion OK — keys: {list(converted.keys())}")
                    dataset_stats[ds_name] = {"status": "OK (dry-run)", "samples": len(samples)}
                else:
                    # Full load
                    print(f"    Loading dataset (max {args.max_per_dataset} samples)...")
                    ds = load_hf_dataset(
                        hf_id, ds_info.get("config"), ds_info["split"],
                        max_samples=args.max_per_dataset,
                    )
                    converter = CONVERTERS[ds_name]
                    converted = []
                    for example in ds:
                        try:
                            rec = converter(example)
                            converted.append(rec)
                        except Exception as e:
                            pass  # Skip malformed records silently
                    all_records.extend(converted)
                    dataset_stats[ds_name] = {"status": "OK", "samples": len(converted)}
                    print(f"    Converted {len(converted)} records")

            except Exception as e:
                print(f"    ERROR: {e}")
                dataset_stats[ds_name] = {"status": f"FAILED: {e}", "samples": 0}

        else:
            # Local ATMAN records
            local_path = ds_info.get("local_path", "data/training")
            print(f"    Local path: {local_path}")

            train_file = Path(local_path) / "train.jsonl"
            val_file = Path(local_path) / "val.jsonl"

            if train_file.exists() or val_file.exists():
                if args.dry_run:
                    count = 0
                    for f in [train_file, val_file]:
                        if f.exists():
                            with open(f) as fh:
                                count += sum(1 for _ in fh)
                    print(f"    [DRY RUN] OK — {count} local records found")
                    dataset_stats[ds_name] = {"status": "OK (dry-run)", "samples": count}
                else:
                    local_recs = load_local_atman(local_path)
                    all_records.extend(local_recs)
                    dataset_stats[ds_name] = {"status": "OK", "samples": len(local_recs)}
                    print(f"    Loaded {len(local_recs)} local records")
            else:
                print(f"    WARNING: No local ATMAN files found at {local_path}")
                print(f"    Run: python scripts/generate_atman_data.py first")
                dataset_stats[ds_name] = {"status": "NO LOCAL FILES", "samples": 0}

    # Summary
    print(f"\n{'=' * 60}")
    print("Dataset Summary:")
    for name, stats in dataset_stats.items():
        print(f"  {name:25s} {stats['status']:20s} ({stats['samples']} samples)")

    if args.dry_run:
        failed = [n for n, s in dataset_stats.items() if "FAILED" in s["status"]]
        if failed:
            print(f"\nFAILED datasets: {', '.join(failed)}")
            print("Fix these before running without --dry-run")
            sys.exit(1)
        else:
            print(f"\nAll datasets verified. Ready for full preparation.")
        return

    if not all_records:
        print("\nNo records collected. Nothing to write.")
        sys.exit(1)

    # Shuffle and split
    random.shuffle(all_records)
    val_count = int(len(all_records) * args.val_split)
    val_records = all_records[:val_count]
    train_records = all_records[val_count:]

    print(f"\nTotal: {len(all_records)} records (train={len(train_records)}, val={len(val_records)})")

    # Tokenize for SamskaraMini autoresearch
    print(f"Tokenizing (max_seq_len={args.max_seq_len})...")
    train_tok, vocab_size, stoi = tokenize_for_autoresearch(train_records, args.max_seq_len)
    val_tok, _, _ = tokenize_for_autoresearch(val_records, args.max_seq_len)

    print(f"  Vocab size: {vocab_size}")
    print(f"  Tokenized train: {len(train_tok)}, val: {len(val_tok)}")

    # Write output
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # Write meta.pkl for train.py consumption
    meta = {
        "vocab_size": vocab_size,
        "stoi": stoi,
        "itos": {i: c for c, i in stoi.items()},
        "train": train_tok,
        "val": val_tok,
    }
    meta_path = output_dir / "meta.pkl"
    with open(meta_path, "wb") as f:
        pickle.dump(meta, f)
    print(f"\nWrote {meta_path}")

    # Write JSONL files for full model training (scripts/train_full.py)
    train_jsonl = output_dir / "combined_train.jsonl"
    val_jsonl = output_dir / "combined_val.jsonl"

    with open(train_jsonl, "w") as f:
        for rec in train_records:
            f.write(json.dumps(rec) + "\n")

    with open(val_jsonl, "w") as f:
        for rec in val_records:
            f.write(json.dumps(rec) + "\n")

    print(f"Wrote {train_jsonl} ({len(train_records)} records)")
    print(f"Wrote {val_jsonl} ({len(val_records)} records)")
    print("\nDone. Data ready for training.")


if __name__ == "__main__":
    main()
